config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :allotments do
    resources :bookings, only: :create
  end
  delete '/bookings/:id', to: 'bookings#destroy', as: 'booking'
  patch '/bookings/:id', to: 'bookings#approve'
  get '/bookings', to: 'bookings#index'
end

app/models/allotment.rb
class Allotment < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, :description, :location, :price, :area_size, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_many_attached :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :allotment
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :allotments
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable    
end

app/controllers/allotments_controller.rb
class AllotmentsController < ApplicationController
  before_action :set_allotment, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @allotments = Allotment.where("location ILIKE ?", "%#{params[:query]}%")
    else
      @allotments = Allotment.all
    end
    @markers = @allotments.geocoded.map do |allotment|
      {
        lat: allotment.latitude,
        lng: allotment.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { allotment: allotment }),
        image_url: helpers.asset_url('icons8-big-carrot-64.png')
      }
    end
  end

  def show
    @booking = Booking.new
    @markers =
      [{
        lat: @allotment.latitude,
        lng: @allotment.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { allotment: @allotment }),
        image_url: helpers.asset_url('icons8-big-carrot-64.png')
      }]
  end

  def new
    @allotment = Allotment.new
  end

  def create
    @allotment = Allotment.create(allotment_params)
    @allotment.user = current_user
    if @allotment.save
      redirect_to allotment_path(@allotment), notice: 'Allotment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @allotment.destroy
    redirect_to allotments_path, notice: 'Allotment was successfully destroyed.'
  end

  def update
    if @allotment.update(allotment_params)
      redirect_to allotment_path(@allotment), notice: 'Allotment was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  private

  def set_allotment
    @allotment = Allotment.find(params[:id])
  end

  def allotment_params
    params.require(:allotment).permit(:name, :description, :location, :price, :area_size, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_allotment, only: %i[create]

  def index
    @my_bookings = current_user.bookings
    @my_allotments = current_user.allotments
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.allotment = @allotment
    @booking.total_price = @allotment.price * ((@booking.end_date.year * 12 + @booking.end_date.month) - (@booking.start_date.year * 12 + @booking.start_date.month))
    if @booking.save
      flash[:notice] = "You have successfully booked #{@allotment.name}"
    else
      flash[:alert] = "Something went wrong. Please check your dates."
    end
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.approved && @booking.allotment.user != current_user
      flash[:alert] = "This booking has already been approved. Please contact the owner of the allotment at #{@booking.allotment.user.email}."
    else
      @booking.destroy
      flash[:alert] = "Your booking for #{@booking.allotment.name} has been deleted."
    end
    redirect_to bookings_path
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.approved = params[:approved]
    if @booking.approved
      if @booking.save
        flash[:notice] = "You have accepted the booking by #{@booking.user.email} for #{@booking.start_date.strftime('%d/%m/%Y')} - #{@booking.end_date.strftime('%d/%m/%Y')}"
      else
        flash[:alert] =
          "Something went wrong. Please try again later. If this issue persists, please contact the support team."
      end
    elsif @booking.approved == false
      if @booking.save
        flash[:alert] = "You have rejected the booking by #{@booking.user.email} for #{@booking.start_date.strftime('%d/%m/%Y')} - #{@booking.end_date.strftime('%d/%m/%Y')}"
      else
        flash[:alert] = "Something went wrong. Please try again later. If this issue persists, please contact the support team."
      end
    end
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_allotment
    @allotment = Allotment.find(params[:allotment_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @allotments = Allotment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/allotments/_form.html.erb
<%= simple_form_for(@allotment) do |f| %>
<div>
  <span>Name: </span>
  <%= f.input :name, label: false %>
</div>
<div>
  <span>Description: </span>
  <%= f.input :description, label: false %>
</div>
<div>
  <span>Location: </span>
  <%= f.input :location, label: false %>
</div>
<div>
  <span>Price: </span>
  <%= f.input :price, label: false %>
</div>
<div>
  <span>Area size: </span>
  <%= f.input :area_size, label: false %>
</div>
<div>
  <span>Photo: </span>
  <%= f.input :photos, label: false, as: :file, input_html: { multiple: true} %>
</div>
<%= f.button :submit, class: "btn btn-flat"%>
<% end %>

app/views/allotments/_info_window.html.erb
<h2><%= allotment.name %></h2>
<p><%= allotment.location %></p>

app/views/allotments/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-xs-12 col-md-8">
      <div class="form-login">
        <div class="form p-5">
          <h2>Editing Allotment</h2>

          <%= render 'form', allotment: @allotment %>

          <%= link_to 'Back', allotment_path(@allotment) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/allotments/index.html.erb
<%= form_tag allotments_path, method: :get do %>
<div class="search-form-control form-group">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find an allotment",
    style: "max-width: 42vw;"
  %>
  <%= submit_tag "Search", class: "btn btn-flat", style: "left: 43vw;" %>
  </div>
<% end %>
<div class="card-box">
  <div class="card">
    <% @allotments.each do |allotment| %>
      <div class="card-product">
        <div class="card-product-img">
        <% if allotment.photos.attached? %>
          <%= cl_image_tag(allotment.photos.first.key,
                width: 400, height: 300, crop: :fill) %>
          <% else %>
            <img src= "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" class="card-product-img">
        <% end %>
      </div>
        <%= link_to allotment_path(allotment), target: "_blank" do%>
          <div class="card-product-infos">
            <div class="card-product-info1">
              <div><h3><%= allotment.name %></h3></div>
              <div><p><%= allotment.description[0, 100] %>...</p></div>
             </div>
             <div class="card-product-info2">
              <div></div>
              <div>
              <p>Size: <%= allotment.area_size%>m<sup>2</sup></p>
              <p>Price: <%= "£#{allotment.price} per month" %></p>
              </div>
              </div>
            </div>
        <% if allotment.user != current_user %>
          <% avatars = ["https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345622/jane_kgqddw.png", "https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345377/john_aj1jop.jpg"] %>
          <img class="card-product-user avatar-bordered" alt="avatar-large" src= <%= avatars.sample %> />
        <% elsif allotment.user == current_user %>
          <img class="card-product-user avatar-bordered" alt="avatar-large" src="https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345377/john_aj1jop.jpg" />
        <% end %>
          <% end %>
      </div>
    <% end %>
  </div>
  <div class="card" id="map" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/allotments/show.html.erb
<div class="container show-background">

  <div class="flex">

    <h1><%# add icon %><%= @allotment.name %><%# add icon %></h1>

  </div>

  <div class="photo-box">
      <% if @allotment.photos.attached? %>
        <%= cl_image_tag(@allotment.photos.first.key,
          crop: :fill, style: "border-radius: 10px;") %>
      <% else %>
         <img src= "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" style="border-radius: 10px;">
      <% end %>
  </div>

  <div class="flex details">
    <div class="description-container">
    <div class="description-header">
      <h4>A little bit about this allotment</h4>
      <div class="description-header-img">
        <% if @allotment.user != current_user %>
        <% avatars = ["https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345622/jane_kgqddw.png", "https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345377/john_aj1jop.jpg"] %>
          <img class="avatar-large" alt="avatar-large" src= <%= avatars.sample%> />
        <% elsif @allotment.user == current_user %>
          <img class="avatar-large" alt="avatar-large" src="https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345377/john_aj1jop.jpg" />
        <% end %>
        <p>Owned by: <%= @allotment.user.email %></p>
      </div>
    </div>
    <div class="description">
      <div>
      <p style="max-width: 40vw;"><%= @allotment.description %></p>
      </div>
      <p><i class="fas fa-street-view"></i> <%= @allotment.location %></p>
      <p><i class="fas fa-ruler-horizontal"></i> Size: <%= @allotment.area_size %>m<sup>2</sup></p>
    </div>
    <div class="description-map">
    <div class="card" id="map"
     style="width: 615px; height: 400px; border-radius: 10px; position: relative; margin-top: 0px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
    </div>

  <% if @allotment.user != current_user %>
  <div>
    <div class="booking">
      <h4>Select dates for prices</h4>
      <h6><strong>£</strong><strong class="price"><%= @allotment.price %></strong> per month</h6>
      <h5 class="totalprice"></h5>
      <%= simple_form_for [@allotment, @booking] do |f| %>
        <span>START DATE</span>
        <%= f.input :start_date, label: false, as: :string, input_html: {class: "datepickerstart"} %>
        <span>END DATE</span>
        <%= f.input :end_date, label: false, as: :string, input_html: {class: "datepickerend"} %>
        <button type="button" class="btn btn-flat book-button" data-toggle="modal" data-target="#exampleModal" disabled>Book</button>
          </div>
      </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Booking Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <%= f.submit class: "btn btn-flat" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>

  <% if @allotment.user == current_user %>
  <div>
    <div class="options">
      <%= link_to edit_allotment_path(@allotment), class: "btn btn-flat" do %>
        <span id="edit"><i class="fas fa-tools"></i> Edit</span>
        <% end %>
      <%= link_to allotment_path(@allotment), method: :delete, data: {confirm: "Are you sure you wish to delete it?"}, class: "btn btn-flat" do %>
        <span id="edit"><i class="fas fa-trash-alt"></i> Delete</span>
        <% end %>
    </div>
    </div>
  <% end %>

  </div>

</div>

app/views/bookings/index.html.erb
<div class="container">
  <ul class="nav nav-tabs mt-4" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="my-bookings-tab" data-toggle="tab" href="#my-bookings" role="tab" aria-controls="my-bookings" aria-selected="true">My bookings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="my-allotment-bookings-tab" data-toggle="tab" href="#my-allotment-bookings" role="tab" aria-controls="my-allotment-bookings" aria-selected="false">My allotment bookings</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show active" id="my-bookings" role="tabpanel" aria-labelledby="my-bookings-tab">
        <% @my_bookings.each do |booking| %>
          <div class="card-product mt-3" style="border-radius: 10px;">
            <% if booking.allotment.photos.attached? %>
              <%= cl_image_tag(booking.allotment.photos.first.key,
                width: 400, height: 300, crop: :fill) %>
            <% else %>
              <img src= "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" width="400" height="300" class="card-product-img">
            <% end %>
            <div class="card-product-infos" style="flex-direction: row;">
              <div class="card-product-info1" style="margin: 20px; max-width: 30vw;">
                <h3><%= booking.allotment.name %></h3>
                <p><%= booking.allotment.description[0..100] %>...</p>
              </div>
              <div class="card-product-info2" style="margin: 20px; flex-direction: column; min-width: 15vw">
                <%= link_to "", booking_path(booking), class: "btn btn-flat fas fa-trash-alt", method: :delete, data: {confirm: "Are you sure you wish to delete your booking?"}  %>
                <p>Dates: <%= booking.start_date.strftime("%d/%m/%Y") %> - <%= booking.end_date.strftime("%d/%m/%Y") %></p>
                <p>Size: <%= booking.allotment.area_size%>m<sup>2</sup></p>
                <p>Total price: <%= "£#{booking.total_price}" %></p>
                <% if booking.approved.nil? %>
                  <p>Status: <em class="approval text-warning">Pending...</em></p>
                <% elsif booking.approved %>
                  <p>Status: <strong class="approval text-success">Accepted</strong></p>
                <% else %>
                  <p>Status: <strong class="approval text-danger">Rejected</strong></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

    </div>

    <div class="tab-pane fade" id="my-allotment-bookings" role="tabpanel" aria-labelledby="my-allotment-bookings-tab">
        <% @my_allotments.each do |allotment| %>
          <% allotment.bookings.each do |booking| %>
                <div class="card-product mt-3" style="border-radius: 10px;">
            <% if booking.allotment.photos.attached? %>
              <%= cl_image_tag(booking.allotment.photos.first.key,
                width: 400, height: 300, crop: :fill) %>
            <% else %>
              <img src= "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" width="400" height="300" class="card-product-img">
            <% end %>
            <div class="card-product-infos" style="flex-direction: row;">
              <div class="card-product-info1" style="margin: 20px; max-width: 30vw;">
                <h3><%= booking.allotment.name %></h3>
                <p><%= booking.allotment.description[0, 100] %>...</p>
                <% if booking.approved.nil? %>
                  <div class="approve-buttons">
                    <%= link_to "Accept", booking_path(booking, approved: true), method: :patch, class: "btn btn-flat ml-4" %>
                    <%= link_to "Reject", booking_path(booking, approved: false), method: :patch, class: "btn btn-danger ml-4" %>
                  </div>
                <% end %>
              </div>
              <div class="card-product-info2" style="margin: 20px; flex-direction: column; min-width: 15vw;">
                <%= link_to "", booking_path(booking), class: "btn btn-flat fas fa-trash-alt", method: :delete, data: {confirm: "Are you sure you wish to delete your booking?"}  %>
                <p>Booked by: <strong><%= booking.user.email%></strong></p>
                <p>Dates: <strong><%= booking.start_date.strftime("%d/%m/%Y") %> - <%= booking.end_date.strftime("%d/%m/%Y") %></strong></p>
                <p>Total price: <%= "£#{booking.total_price}" %></p>
                <% if booking.approved.nil? %>
                  <p>Status: <em class="approval text-warning">Pending...</em></p>
                <% elsif booking.approved %>
                  <p>Status: <strong class="approval text-success">Accepted</strong></p>
                <% else %>
                  <p>Status: <strong class="approval text-danger">Rejected</strong></p>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532434418666-NN9YN6901LFCO43GZYBZ/ke17ZwdGBToddI8pDm48kMW-P9pta-BYWZxEMI3BKYl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0p4Wyba38KfG317vYluk45-p5WWTS4f4Tp1l_ud6gYH9Cc-xG3LLbueyNfhvXi2kmg/2-L1009592-Edit.jpg?format=2500w')">
<div class="container"><h1>GroundBnB</h1>
<p>Rent an allotment through GroundBnB to grow your own fruit and vegetables</p></div></div>

<%= form_tag allotments_path, method: :get do %>
<div class="search-form-control form-group">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find an allotment"
  %>
  <%= submit_tag "Search", class: "btn btn-flat" %>
  </div>
<% end %>

  <div class="slide">
    <div class="content-title">
        <h1>Become an owner</h1>
        <p>Create a new allotment</p>
        <%= link_to "Get Started", new_allotment_path, class: "btn btn-flat"%>
    </div>
    <div class="content">
      <div class="images">
        <img class="slide-image" src="https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532435360584-O4OUYYF2YPO5EFQP5DK2/ke17ZwdGBToddI8pDm48kFWxnDtCdRm2WA9rXcwtIYR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UcTSrQkGwCGRqSxozz07hWZrYGYYH8sg4qn8Lpf9k1pYMHPsat2_S1jaQY3SwdyaXg/114-L1050990.jpg?format=2500w">
        <img class="slide-image" src="https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532435348536-XTY5VRDUDDRY3CM02EMF/ke17ZwdGBToddI8pDm48kFWxnDtCdRm2WA9rXcwtIYR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UcTSrQkGwCGRqSxozz07hWZrYGYYH8sg4qn8Lpf9k1pYMHPsat2_S1jaQY3SwdyaXg/112-L1050983.jpg?format=2500w">
        <img class="slide-image" src="https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532435556391-YZS4FIBZPSJDIBCDVGH7/ke17ZwdGBToddI8pDm48kFWxnDtCdRm2WA9rXcwtIYR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UcTSrQkGwCGRqSxozz07hWZrYGYYH8sg4qn8Lpf9k1pYMHPsat2_S1jaQY3SwdyaXg/102-B40I1541.jpg?format=2500w">
        <img class="slide-image" src="https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532435349068-T3TAJ6X5P02SXQ3E29RE/ke17ZwdGBToddI8pDm48kM7lIDFHi7UQLNQSFuB5lX4UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcevyHm_O1XoLPZqNjlvbO_6BXwzQSYyfdy-MonM784I1BD3hfTTPzV4wkkFabvReX/113-L1050984.jpg?format=2500w">
        <img class="slide-image" src="https://images.squarespace-cdn.com/content/v1/5b10053a2487fdb5e3fe4b16/1532435588225-3278NQBFEZJTZQ85IVHZ/ke17ZwdGBToddI8pDm48kFWxnDtCdRm2WA9rXcwtIYR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UcTSrQkGwCGRqSxozz07hWZrYGYYH8sg4qn8Lpf9k1pYMHPsat2_S1jaQY3SwdyaXg/22-L1009685.jpg?format=2500w">
      </div>
    </div>
</div>
<div style="text-align: center; padding:20px;">
  <h1>Why us?</h1>
</div>
  <div class="container top-container">
    <div class="row">
      <div class="column">
        <div class="far fa-hospital">
        </div>
        <h2>Safe</h2>
        <p>Our chemists team run monthly test on each allotments, ensuring the soil is contamination-free and allowing your plants to grow healthy just like Mothe Nature wants!</p>
      </div>
      <div class="column" >
        <div class="far fa-lightbulb">
        </div>
        <h2>Innovative</h2>
        <p>We are the the first app that let you hire the allotment you've always dreamt about in a blink of an eye.</p>
      </div>
      <div class="column">
        <div class="far fa-heart">
        </div>
        <h2>Caring</h2>
        <p>Our gardeners team will prepare the ground before you settle in your new piece of land, making sure your experience will have the best start possible.</p>
      </div>
    </div>
  </div>

<%# <h3>Top-rated Allotments</h3>
    <div class="row">
      <% @allotments.each do |allotment| %>
        <%# <div class="col card-trip">
          <% if allotment.photos.attached? %>
            <%# <%= cl_image_tag(allotment.photos.first.key, crop: :fill) %> 
          <%# <% else %> 
            <%# <img src= "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" width="400" height="300"> %>
          <%# <% end %> 
            <%# <%= link_to allotment_path(allotment) do  %>
        <%# <div class="card-trip-infos"> %>
          <%# <div><%= allotment.name</div>  %>
          <%# <div>Location: <%= allotment.location</div>  %>
          <%# <div><%= allotment.description[0, 100]...</div> %>
          <%# <div>Size: <%= allotment.area_sizem<sup>2</sup></div>  %>
        <%# </div> %>
        <%# <% end %>
      <%# </div> %>
      <%# <% end %>
    <%# </div> %> 

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "btn btn-flat" do %>
    <img src="https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614182368/farming_nj7zjh.png" class="logo" alt="logo">GroundBnB
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-list-4">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614345377/john_aj1jop.jpg" width="40" height="40" class="rounded-circle">
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Rent your allotment", new_allotment_path, class: "dropdown-item"%>
            <%= link_to "Browse all gardens", allotments_path, class: "dropdown-item" %>
            <%= link_to "Allotments and Bookings", bookings_path, class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
          </div>
        </li>   
      </ul>
   </div>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "btn btn-flat" do %>
      <img src="https://res.cloudinary.com/dx6rtf9wl/image/upload/v1614182368/farming_nj7zjh.png" class="logo" alt="logo">GroundBnB
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div>
      <%= link_to "Browse all gardens", allotments_path, class: "btn btn-outline-success" %>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn-flat" %>
    </div>
  </div>
<% end %>